# Generated by Django 3.2.5 on 2021-08-31 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='project.report')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=400, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('regulations', models.CharField(max_length=200)),
                ('lat', models.CharField(blank=True, max_length=326, null=True)),
                ('lon', models.CharField(blank=True, max_length=326, null=True)),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('founders_name', models.ManyToManyField(related_name='founders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
