# Generated by Django 3.2.5 on 2021-09-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210902_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='project',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
