# Generated by Django 3.2.5 on 2021-10-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210914_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(choices=[('ah', 'AHAFO'), ('as', 'ASHANTI'), ('bo', 'BONO'), ('be', 'BONO EAST'), ('ce', 'CENTRAL'), ('ea', 'EASTERN'), ('ga', 'GREATER ACCRA'), ('ne', 'NORTH EAST'), ('no', 'NORTHERN'), ('ot', 'OTI'), ('sa', 'SAVANNAH'), ('ue', 'UPPER EAST'), ('uw', 'UPPER WEST'), ('ws', 'WESTERN SEKONDI'), ('wn', 'WESTERN NORTH'), ('vo', 'VOLTA')], default='ga', max_length=2, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('PRESIDENTIAL PITCH', 'PRESIDENTIAL PITCH'), ('BUSINESS SUPPORT PROGRAMME', 'BUSINESS SUPPORT PROGRAMME'), ('PRESIDENTIAL EMPOWERMENT INITIATIVE', 'SEI'), ('PRESIDENTIAL EMPOWERMENT FOR WOMEN ENTREPRENEURS WITH DISABILITY', 'PEWED'), ('PRESIDENTIAL EMPOWERMENT FOR MALE ENTERPRENEURS WITH DISABILITY', 'PEMED'), ('SPECIAL PROJECTS (PARTNERSHIP)', 'PARTNERSHIP')], default='PRESIDENTIAL PITCH', max_length=100, null=True),
        ),
    ]
