# Generated by Django 3.2.5 on 2021-08-26 10:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_alter_person_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='primary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='primary phone number'),
        ),
        migrations.AddField(
            model_name='person',
            name='secondary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='secondary phone number'),
        ),
    ]
