# Generated by Django 3.2.5 on 2021-08-31 03:18

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='first names')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last names')),
                ('other_names', models.CharField(blank=True, max_length=100, null=True, verbose_name='other names')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('region', models.CharField(choices=[('ah', 'AHAFO'), ('as', 'ASHANTI'), ('be', 'BONO EAST'), ('ba', 'BRONG AHAFO'), ('ce', 'CENTRAL'), ('ea', 'EASTERN'), ('ga', 'GREATER ACCRA'), ('ne', 'NORTH EAST'), ('no', 'NORTHERN'), ('ot', 'OTI'), ('sa', 'SAVANNAH'), ('ue', 'UPPER EAST'), ('uw', 'UPPER WEST'), ('ws', 'WESTERN SEKONDI'), ('wn', 'WESTERN NORTH'), ('vo', 'VOLTA')], default='ga', max_length=2, verbose_name='region')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('primary_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='primary phone number')),
                ('secondary_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='secondary phone number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='profile create date')),
                ('status', models.CharField(choices=[('trainee', 'TRAINEE'), ('completed', 'COMPLETED')], default='trainee', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
