# Generated by Django 3.2.5 on 2021-10-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_person_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default='bangaImages/default.jpg', upload_to='media/img/avatar'),
        ),
    ]
