# Generated by Django 3.2.5 on 2021-10-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0003_alter_person_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default='media/img/avatar/default.jpg', upload_to='media/img/avatar'),
        ),
    ]
