# Generated by Django 3.2.5 on 2022-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0004_alter_person_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(default='CEO', max_length=30),
        ),
    ]
